
import React, { useState, useEffect, useCallback } from 'react';
import Checkbox from './components/Checkbox';
import NumberInput from './components/NumberInput';
import CodeBlock from './components/CodeBlock';
import { DATA_POINTS } from './constants';
import type { AppConfig } from './types';

const TextInput: React.FC<{id: string, label: string, value: string, onChange: (value: string) => void, placeholder?: string, helpText?: string}> = ({ id, label, value, onChange, placeholder, helpText }) => (
    <div>
      <label htmlFor={id} className="block text-sm font-medium text-gray-400 mb-1">
        {label}
      </label>
      <input
        type="text"
        id={id}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="w-full bg-gray-800 border border-gray-700 text-white rounded-md px-3 py-2 text-base shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition"
      />
      {helpText && <p className="mt-1 text-xs text-gray-500">{helpText}</p>}
    </div>
);


const App: React.FC = () => {
  const [config, setConfig] = useState<AppConfig>({
    serviceUUID: '0000ffe0-0000-1000-8000-00805f9b34fb',
    characteristicUUID: '0000ffec-0000-1000-8000-00805f9b34fb',
    wheelCircumference: 1.416,
    motorPolePairs: 20,
    enableSDLogging: false,
    logFileName: 'datalog.csv',
    sdCsPin: 5,
    selectedDataPoints: ['voltage', 'rpm', 'speed', 'soc'],
  });
  const [generatedCode, setGeneratedCode] = useState('');

  const handleDataPointChange = (id: string, checked: boolean) => {
    setConfig((prevConfig) => {
      const selected = new Set(prevConfig.selectedDataPoints);
      if (checked) {
        selected.add(id);
      } else {
        selected.delete(id);
      }
      return { ...prevConfig, selectedDataPoints: Array.from(selected) };
    });
  };

  const generateArduinoCode = useCallback((currentConfig: AppConfig) => {
    const { 
        serviceUUID, characteristicUUID, 
        wheelCircumference, motorPolePairs,
        enableSDLogging, logFileName, sdCsPin,
        selectedDataPoints 
    } = currentConfig;
    
    if (selectedDataPoints.length === 0 && !enableSDLogging) {
        return `// Select at least one data point to generate code.`;
    }

    const header = `/*
 * ESP32 Fardriver BLE Data Logger
 * Generated by the Fardriver Code Generator app
 * 
 * This code connects to a Fardriver controller via Bluetooth Low Energy (BLE),
 * decodes the data stream, and prints it to the Serial Monitor.
 * It can also log the data to a MicroSD card if enabled.
 */

// 1. LIBRARIES
#include <Arduino.h>
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEScan.h>
#include <BLEAdvertisedDevice.h>
${enableSDLogging ? `
#include <SPI.h>
#include <SD.h>
` : ''}
// --- BLE Configuration ---
#define SERVICE_UUID        "${serviceUUID}"
#define CHARACTERISTIC_UUID "${characteristicUUID}"
${enableSDLogging ? `
// --- SD Card Configuration ---
#define SD_CS_PIN ${sdCsPin}
const char* logFileName = "/${logFileName}";
` : ''}
// --- Vehicle Configuration ---
const float wheel_circumference_m = ${wheelCircumference};
const int motor_pole_pairs = ${motorPolePairs};
`;

    const dataStructure = `
// 2. Fardriver Data Structure & Global Variables
struct FardriverData {
  float voltage = 0;
  float lineCurrent = 0;
  float power = 0;
  float rpm = 0;
  int16_t rawRpm = 0;
  int gear = 0;
  float speed = 0;
  int controllerTemp = 0;
  int motorTemp = 0;
  int soc = 0;
  bool isRegenFromCurrent = false;
};

FardriverData controllerData;
static BLEAdvertisedDevice* myDevice = nullptr;
static BLEClient* pClient = nullptr;
static BLERemoteCharacteristic* pRemoteCharacteristic = nullptr;
static bool connected = false;
static bool needsToScan = true;
static bool newDataAvailable = false;

unsigned long lastPrintTime = 0;
const unsigned long printInterval = 500; // Print data every 500ms

const uint8_t flash_read_addr[55] = {
  0xE2, 0xE8, 0xEE, 0xE4, 0x06, 0x0C, 0x12, 0xE2, 0xE8, 0xEE, 0x18, 0x1E, 0x24, 0x2A,
  0xE2, 0xE8, 0xEE, 0x30, 0x5D, 0x63, 0x69, 0xE2, 0xE8, 0xEE, 0x7C, 0x82, 0x88, 0x8E,
  0xE2, 0xE8, 0xEE, 0x94, 0x9A, 0xA0, 0xA6, 0xE2, 0xE8, 0xEE, 0xAC, 0xB2, 0xB8, 0xBE,
  0xE2, 0xE8, 0xEE, 0xC4, 0xCA, 0xD0, 0xE2, 0xE8, 0xEE, 0xD6, 0xDC, 0xF4, 0xFA
};

// 3. FUNCTION PROTOTYPES
void processPacket(uint8_t* pData, size_t length);
bool verifyCRC(uint8_t* data, uint16_t length);
bool connectToServer();
void startScan();
void printControllerData();
${enableSDLogging ? `void initSDCard();\nvoid logDataToSD();` : ''}
`;

const sdCardFunctions = enableSDLogging ? `
// 4. SD CARD FUNCTIONS
void initSDCard() {
  Serial.print("Initializing SD card...");
  if (!SD.begin(SD_CS_PIN)) {
    Serial.println(" initialization failed!");
    while (1);
  }
  Serial.println(" initialization done.");

  File dataFile = SD.open(logFileName, FILE_READ);
  if (!dataFile) {
    Serial.println("Log file not found, creating header...");
    dataFile = SD.open(logFileName, FILE_WRITE);
    if (dataFile) {
      String header = "timestamp";
      ${selectedDataPoints.map(id => `header += ",${id}";`).join('\n      ')}
      dataFile.println(header);
      dataFile.close();
      Serial.println("Header created.");
    } else {
      Serial.println("Error creating log file!");
    }
  } else {
      dataFile.close();
  }
}

void logDataToSD() {
  File dataFile = SD.open(logFileName, FILE_APPEND);
  if (dataFile) {
    String dataString = String(millis());
    ${selectedDataPoints.map(id => `dataString += "," + String(controllerData.${id});`).join('\n    ')}
    dataFile.println(dataString);
    dataFile.close();
  } else {
    Serial.println("Error opening log file for appending.");
  }
}
` : '';

const bleCallbacks = `
// 5. BLE CALLBACKS
static void notifyCallback(BLERemoteCharacteristic* pBLERemoteCharacteristic, uint8_t* pData, size_t length, bool isNotify) {
  processPacket(pData, length);
}

class MyClientCallback : public BLEClientCallbacks {
  void onConnect(BLEClient* pclient_cb) {
    connected = true;
    needsToScan = false;
  }
  void onDisconnect(BLEClient* pclient_cb) {
    connected = false;
    if (myDevice != nullptr) {
        delete myDevice;
        myDevice = nullptr;
    }
    needsToScan = true;
  }
};

class MyAdvertisedDeviceCallbacks : public BLEAdvertisedDeviceCallbacks {
  void onResult(BLEAdvertisedDevice advertisedDevice) {
    if (advertisedDevice.haveServiceUUID() && advertisedDevice.isAdvertisingService(BLEUUID(SERVICE_UUID))) {
      if (myDevice == nullptr) {
        myDevice = new BLEAdvertisedDevice(advertisedDevice);
        BLEDevice::getScan()->stop();
        needsToScan = false;
      }
    }
  }
};
`;

const dataProcessing = `
// 6. DATA PROCESSING & VALIDATION
void processPacket(uint8_t* packet, size_t length) {
  if (!verifyCRC(packet, length)) return;
  uint8_t id = packet[1] & 0x3F;
  if (id >= sizeof(flash_read_addr)) return;
  uint8_t address = flash_read_addr[id];
  uint8_t* pData = &packet[2];
  switch (address) {
    case 0xE2:
      controllerData.gear = ((pData[0] >> 2) & 0b11) + 1;
      controllerData.rawRpm = (int16_t)((pData[7] << 8) | pData[6]);
      break;
    case 0xE8: {
      float new_voltage = ((pData[1] << 8) | pData[0]) / 10.0f;
      if (new_voltage >= 0 && new_voltage <= 100.0f) { controllerData.voltage = new_voltage; }
      
      float new_lineCurrent = (int16_t)((pData[5] << 8) | pData[4]) / 4.0f;
      if (new_lineCurrent >= -100.0f && new_lineCurrent <= 300.0f) { 
          controllerData.lineCurrent = new_lineCurrent; 
      }
      
      controllerData.isRegenFromCurrent = (controllerData.lineCurrent < 0);
      break;
    }
    case 0xD6: {
      int new_controllerTemp = (int16_t)((pData[11] << 8) | pData[10]);
      if (new_controllerTemp > -20 && new_controllerTemp < 100) { controllerData.controllerTemp = new_controllerTemp; }
      break;
    }
    case 0xF4: {
      int new_motorTemp = (int16_t)((pData[1] << 8) | pData[0]);
      if (new_motorTemp > -20 && new_motorTemp < 200) { controllerData.motorTemp = new_motorTemp; }
      controllerData.soc = pData[3];
      break;
    }
  }
  
  int16_t displayRawRpm = (controllerData.rawRpm < 0) ? 0 : controllerData.rawRpm;
  controllerData.rpm = displayRawRpm * 4.0 / motor_pole_pairs;
  controllerData.speed = (controllerData.rpm * wheel_circumference_m * 60.0) / 1000.0;
  
  if (controllerData.voltage > 0) {
    controllerData.power = controllerData.voltage * controllerData.lineCurrent;
  }
  
  newDataAvailable = true;
}

bool verifyCRC(uint8_t* data, uint16_t length) {
  if (length != 16) return false;
  uint16_t crc = 0x7F3C;
  for (int i = 0; i < 14; i++) {
    crc ^= data[i];
    for (int j = 0; j < 8; j++) {
      crc = (crc & 1) ? (crc >> 1) ^ 0xA001 : crc >> 1;
    }
  }
  return crc == ((data[15] << 8) | data[14]);
}
`;
const bleHelpers = `
// 7. BLE HELPER FUNCTIONS
void startScan() {
  if (myDevice != nullptr) {
    delete myDevice;
    myDevice = nullptr;
  }
  Serial.println("Starting BLE scan...");
  BLEDevice::getScan()->start(0, nullptr, false);
}

bool connectToServer() {
  if (!pClient->connect(myDevice)) {
    return false;
  }
  BLERemoteService* pRemoteService = pClient->getService(BLEUUID(SERVICE_UUID));
  if (!pRemoteService) {
    pClient->disconnect();
    return false;
  }
  pRemoteCharacteristic = pRemoteService->getCharacteristic(BLEUUID(CHARACTERISTIC_UUID));
  if (!pRemoteCharacteristic) {
    pClient->disconnect();
    return false;
  }
  if (pRemoteCharacteristic->canNotify()) {
    pRemoteCharacteristic->registerForNotify(notifyCallback);
  }
  return true;
}
`;

    const serialOutput = `
// 8. SERIAL OUTPUT FUNCTION
void printControllerData() {
  Serial.println("--- Fardriver Controller Data ---");
  ${selectedDataPoints.map(id => {
      const dp = DATA_POINTS.find(p => p.id === id);
      if (!dp) return '';
      if(id === 'isRegenFromCurrent') {
          return `Serial.print("${dp.label}: "); Serial.println(controllerData.${id} ? "Yes" : "No");`;
      }
      return `Serial.print("${dp.label}: "); Serial.print(controllerData.${id}); Serial.println(" ${dp.unit}");`;
  }).join('\n  ')}
  Serial.println("--------------------------------");
}
`;

    const setupAndLoop = `
// 9. SETUP FUNCTION
void setup(void) {
  Serial.begin(115200);
  Serial.println("Starting ESP32 Fardriver BLE Client...");

  ${enableSDLogging ? 'initSDCard();\n' : ''}
  BLEDevice::init("ESP32 Fardriver Client");
  pClient = BLEDevice::createClient();
  pClient->setClientCallbacks(new MyClientCallback());
  BLEScan* pBLEScan = BLEDevice::getScan();
  pBLEScan->setAdvertisedDeviceCallbacks(new MyAdvertisedDeviceCallbacks());
  pBLEScan->setActiveScan(true);
}

// 10. MAIN LOOP
void loop(void) {
  if (needsToScan && !connected) {
    startScan();
    needsToScan = false;
  }

  if (myDevice != nullptr && !connected) {
    if (connectToServer()) {
      Serial.println("Connected to Fardriver Controller");
    } else {
      Serial.println("Failed to connect, will re-scan...");
      delete myDevice;
      myDevice = nullptr;
      needsToScan = true;
    }
  }
  
  if (connected && newDataAvailable) {
    unsigned long currentTime = millis();
    if (currentTime - lastPrintTime > printInterval) {
      printControllerData();
      ${enableSDLogging ? 'logDataToSD();' : ''}
      lastPrintTime = currentTime;
    }
    newDataAvailable = false;
  }
  
  if(!connected) {
      // Small delay to prevent spamming "Scanning..." if no device is found
      delay(2000);
      Serial.println("Scanning for Fardriver Controller...");
  }
  
  delay(20);
}
`;

    return [header, dataStructure, sdCardFunctions, bleCallbacks, dataProcessing, bleHelpers, serialOutput, setupAndLoop].join('\n\n');
  }, []);

  useEffect(() => {
    const code = generateArduinoCode(config);
    setGeneratedCode(code);
  }, [config, generateArduinoCode]);

  return (
    <div className="min-h-screen bg-gray-900 text-gray-200 p-4 sm:p-6 lg:p-8">
      <div className="max-w-7xl mx-auto">
        <header className="text-center mb-8">
          <h1 className="text-4xl font-bold text-white tracking-tight">ESP32 Fardriver BLE Logger</h1>
          <p className="mt-2 text-lg text-gray-400">Code Generator for Wireless Data Logging</p>
        </header>

        <main className="grid grid-cols-1 lg:grid-cols-2 gap-8 h-[calc(100vh-150px)]">
          {/* Left Panel: Configuration */}
          <div className="flex flex-col space-y-8 bg-gray-800/50 p-6 rounded-lg overflow-y-auto">
            <section>
              <h2 className="text-2xl font-semibold text-white border-b-2 border-gray-700 pb-2 mb-4">BLE Configuration</h2>
              <div className="grid grid-cols-1 gap-4">
                 <TextInput
                  id="service-uuid"
                  label="Service UUID"
                  value={config.serviceUUID}
                  onChange={(val) => setConfig({ ...config, serviceUUID: val })}
                  helpText="Use a BLE scanner app like nRF Connect to find your controller's UUIDs."
                />
                <TextInput
                  id="characteristic-uuid"
                  label="Characteristic UUID"
                  value={config.characteristicUUID}
                  onChange={(val) => setConfig({ ...config, characteristicUUID: val })}
                />
              </div>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-white border-b-2 border-gray-700 pb-2 mb-4">Vehicle Parameters</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <NumberInput
                  id="wheel-circ"
                  label="Wheel Circumference (m)"
                  value={config.wheelCircumference}
                  onChange={(val) => setConfig({ ...config, wheelCircumference: val })}
                />
                <NumberInput
                  id="pole-pairs"
                  label="Motor Pole Pairs"
                  value={config.motorPolePairs}
                  onChange={(val) => setConfig({ ...config, motorPolePairs: val })}
                />
              </div>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-white border-b-2 border-gray-700 pb-2 mb-4">SD Card Logging</h2>
              <div className="space-y-4">
                <Checkbox
                    id="enable-sd"
                    label="Enable MicroSD Card Logging"
                    checked={config.enableSDLogging}
                    onChange={(checked) => setConfig(c => ({...c, enableSDLogging: checked}))}
                  />
                  {config.enableSDLogging && (
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pl-8">
                       <TextInput
                          id="log-filename"
                          label="Log Filename"
                          value={config.logFileName}
                          onChange={(val) => setConfig({ ...config, logFileName: val })}
                        />
                        <NumberInput
                          id="sd-cs-pin"
                          label="SD Card CS Pin"
                          value={config.sdCsPin}
                          onChange={(val) => setConfig({ ...config, sdCsPin: val })}
                        />
                    </div>
                  )}
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white border-b-2 border-gray-700 pb-2 mb-4">Data Points to Log & Print</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {DATA_POINTS.map((point) => (
                  <Checkbox
                    key={point.id}
                    id={point.id}
                    label={point.label}
                    checked={config.selectedDataPoints.includes(point.id)}
                    onChange={(checked) => handleDataPointChange(point.id, checked)}
                  />
                ))}
              </div>
            </section>
          </div>

          {/* Right Panel: Code Output */}
          <div className="h-full">
            <CodeBlock code={generatedCode} />
          </div>
        </main>
      </div>
    </div>
  );
};

export default App;
